export const defaultValues = [
  {
    id: 1,
    firstName: "Anna",
    lastName: "Kowalska",
    imgUrl: "https://randomuser.me/api/portraits/women/1.jpg",
    description: "Frontend developerka z doświadczeniem w React i Vue.",
    job: "Frontend Developer",
    gitUrl: "https://github.com/annakowalska",
    linkedinUrl: "https://linkedin.com/in/annakowalska",
    linkedinId: "annakowalska",
  },
  {
    id: 2,
    firstName: "Jan",
    lastName: "Nowak",
    imgUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    description: "Backend developer specjalizujący się w Node.js i Go.",
    job: "Backend Developer",
    gitUrl: "https://github.com/jannowak",
    linkedinUrl: "https://linkedin.com/in/jannowak",
    linkedinId: "jannowak",
  },
  {
    id: 3,
    firstName: "Maria",
    lastName: "Wiśniewska",
    imgUrl: "https://randomuser.me/api/portraits/women/3.jpg",
    description: "UX/UI designer z pasją do użyteczności i estetyki.",
    job: "UX/UI Designer",
    linkedinUrl: "https://linkedin.com/in/mwisniewska",
    linkedinId: "mwisniewska",
  },
  {
    id: 4,
    firstName: "Tomasz",
    lastName: "Zieliński",
    imgUrl: "https://randomuser.me/api/portraits/men/4.jpg",
    description: "DevOps engineer z doświadczeniem w AWS i Docker.",
    job: "DevOps Engineer",
    gitUrl: "https://github.com/tzielinski",
    linkedinUrl: "https://linkedin.com/in/tzielinski",
    linkedinId: "tzielinski",
  },
  {
    id: 5,
    firstName: "Katarzyna",
    lastName: "Wójcik",
    imgUrl: "https://randomuser.me/api/portraits/women/5.jpg",
    job: "Product Manager",
    linkedinUrl: "https://linkedin.com/in/kwojcik",
    linkedinId: "kwojcik",
  },
  {
    id: 6,
    firstName: "Paweł",
    lastName: "Kamiński",
    imgUrl: "https://randomuser.me/api/portraits/men/6.jpg",
    description: "Programista Python z doświadczeniem w AI i ML.",
    job: "ML Engineer",
    gitUrl: "https://github.com/pkaminski",
    linkedinUrl: "https://linkedin.com/in/pkaminski",
    linkedinId: "pkaminski",
  },
  {
    id: 7,
    firstName: "Joanna",
    lastName: "Dąbrowska",
    imgUrl: "https://randomuser.me/api/portraits/women/7.jpg",
    job: "QA Engineer",
    description: "Specjalistka ds. testów automatycznych i manualnych.",
    linkedinUrl: "https://linkedin.com/in/jdabrowska",
    linkedinId: "jdabrowska",
  },
  {
    id: 8,
    firstName: "Michał",
    lastName: "Lewandowski",
    imgUrl: "https://randomuser.me/api/portraits/men/8.jpg",
    job: "Fullstack Developer",
    gitUrl: "https://github.com/mlewandowski",
    linkedinUrl: "https://linkedin.com/in/mlewandowski",
    linkedinId: "mlewandowski",
  },
  {
    id: 9,
    firstName: "Aleksandra",
    lastName: "Szymańska",
    imgUrl: "https://randomuser.me/api/portraits/women/9.jpg",
    job: "Scrum Master",
    linkedinUrl: "https://linkedin.com/in/aszumanska",
    linkedinId: "aszumanska",
  },
  {
    id: 10,
    firstName: "Adam",
    lastName: "Kaczmarek",
    imgUrl: "https://randomuser.me/api/portraits/men/10.jpg",
    job: "System Architect",
    description: "Architekt systemowy z ponad 10-letnim doświadczeniem.",
    linkedinUrl: "https://linkedin.com/in/akaczmarek",
    linkedinId: "akaczmarek",
  },
];
